"""Publishing: release approved drafts.

The website reads published content from Postgres at build time, so publishing a blog post or
episode is: enforce the approval gate, flip the draft (and episode) to ``published``, record a
publication row, and trigger a site rebuild. The newsletter additionally becomes a Listmonk
campaign. The RSS + iTunes feeds are regenerated by the Astro build, and blog/podcast pages for
the same topic already cross-link.

Nothing publishes unless it was approved in the review dashboard (task group 5) — the gate lives
in repository.publish_draft via review.assert_publishable.
"""

from __future__ import annotations

import logging

from . import repository as repo
from .config import get_settings
from .db import get_conn

log = logging.getLogger("boosternews.publish")


def _lang_prefix(language: str) -> str:
    """URL prefix for a language ('' for the primary pt-BR, '/en' for secondary)."""
    return "" if language == get_settings().primary_language_code else f"/{language}"


def publish_topic(topic_id: str) -> dict[str, str]:
    """Publish every approved draft of a topic across all languages. Returns a summary."""
    settings = get_settings()
    drafts = repo.get_topic_drafts(topic_id)
    if not drafts:
        raise ValueError(f"no drafts for topic {topic_id}")

    approved = [d for d in drafts if d["status"] == "approved"]

    # Newsletters are NOT emailed per post — the weekly digest (boosternews.digest) aggregates the
    # last 7 days of posts into one campaign per language. Publishing just releases the blurb so the
    # digest can pick it up.

    summary: dict[str, str] = {}
    with get_conn() as conn:
        for d in drafts:
            key = f"{d['channel']}/{d['language']}"
            if d["status"] != "approved":
                summary[key] = f"skipped ({d['status']})"
                continue

            repo.publish_draft(conn, d["id"])  # gate-enforced
            prefix = _lang_prefix(d["language"])
            if d["channel"] == "podcast":
                repo.publish_episode(conn, topic_id, d["language"])
                url = f"{settings.public_site_url.rstrip('/')}{prefix}/podcast/{topic_id}"
                repo.record_publication(
                    conn, topic_id, "podcast", d["id"], url, None, d["language"]
                )
                summary[key] = "published"
            elif d["channel"] == "newsletter":
                # No per-post campaign; the weekly digest emails subscribers.
                repo.record_publication(
                    conn, topic_id, "newsletter", d["id"], None, None, d["language"]
                )
                summary[key] = "published (weekly digest)"
            else:  # blog
                url = f"{settings.public_site_url.rstrip('/')}{prefix}/blog/{topic_id}"
                repo.record_publication(conn, topic_id, "blog", d["id"], url, None, d["language"])
                summary[key] = "published"
        conn.commit()

    log.info("published topic %s: %s", topic_id, summary)
    return summary


def publish_all() -> dict[str, dict[str, str]]:
    """Publish every topic that has an approved draft. Returns {topic_id: summary}."""
    results: dict[str, dict[str, str]] = {}
    for topic_id in repo.topics_with_approved():
        results[topic_id] = publish_topic(topic_id)
    return results
